---
- name: creating user
  hosts: all
  gather_facts: no
  become: true
  #vars:
   # user_name: krishna
  vars_files: 
      - /home/ansadmin/playbooks/username
  tasks:
  - name: creating user {{user_name}}
    user: 
      name: "{{user_name}}"

  - name: create a directory
    file:
      path: /opt/{{user_name}}_dir
      state: directory
      owner: "{{user_name}}"
      group: "{{user_name}}"
      mode: 0755
