---
- name: install jenkins
  hosts: testteam
  become: true
  gather_facts: no
 
  tasks:
  - name: install java and wget
    yum:
      name: 
        - java-1.8.0-openjdk
        - wget
      state: installed
  
  - name: downloading jenkins repo
    get_url:
      url: https://pkg.jenkins.io/redhat/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  
  - name: adding jenkins key
    rpm_key: 
     state: present
     key: https://pkg.jenkins.io/redhat/jenkins.io.key
 
  - name: install jenkins
    yum: 
      name: jenkins
      state: installed

  - name: start jenkins services
    service:
       name: jenkins
       state: started
       enabled: yes
